'use strict';
/* ======================================================================
   THE TEST GROUP -- generated by tools/generate.js from tools/example-answers.json
   Do not hand-edit lightly -- re-running the generator will overwrite this
   file. See FULFILLMENT.md for the human-review steps this still needs
   before an order is actually delivered (content review is NOT automated).
   ====================================================================== */
const CONFIG = {
  "gameId": "test-group",
  "lengthPreset": "five_min",
  "title": {
    "lockupLines": [
      "THE TEST",
      "GROUP"
    ],
    "introPageTitle": "The Test Group",
    "gamePageTitle": "The Test Group -- Playable Demo"
  },
  "punchline": "SO TRUE.",
  "host": {
    "name": "JORDAN"
  },
  "music": {
    "customSongPath": null,
    "loops": {
      "dinner": "../../../assets/audio/music/farm-frolics.ogg",
      "boss": "../../../assets/audio/music/italian-mom.ogg",
      "chase": "../../../assets/audio/music/retro-reggae.ogg",
      "celebration": "../../../assets/audio/music/night-at-the-beach.ogg",
      "sad": "../../../assets/audio/music/sad-descent.ogg",
      "gameover": "../../../assets/audio/music/game-over.ogg"
    },
    "introFallback": "../../../assets/audio/music/night-at-the-beach.ogg"
  },
  "forbiddenWords": [],
  "stories": [
    {
      "lines": [
        "I MISSED MY FLIGHT BY FOUR MINUTES."
      ]
    },
    {
      "lines": [
        "I ALPHABETIZED THE SPICE RACK WHILE",
        "WE WERE ON HOLD."
      ]
    }
  ],
  "cast": {
    "diner0": {
      "name": "THE FOURTH FRIEND",
      "spriteCol": 1,
      "spriteRow": 7,
      "anecdote": "Always up for anything."
    },
    "judge": null,
    "authority": null,
    "savior": null,
    "butterfingers": {
      "name": "MORGAN",
      "anecdote": "Takes 40 photos of every plate.",
      "spriteCol": 3,
      "spriteRow": 8
    },
    "builder": {
      "name": "RILEY",
      "anecdote": "Builds something every time we hang out.",
      "spriteCol": 2,
      "spriteRow": 8
    }
  },
  "dismissiveLine": "OKAY. WE GET IT.",
  "judge": {
    "title": "THE CRITIC",
    "cardBody": [
      "DODGE THE REVIEWS.",
      "GRAB THE ITEM ON THE FLOOR.",
      "SPACE TO THROW."
    ],
    "critiqueLines": [
      [
        "WEAK PREMISE."
      ],
      [
        "DERIVATIVE."
      ],
      [
        "COULD BE BETTER."
      ]
    ],
    "duckLines": [
      "TOO SLOW, {HOST}.",
      "PREDICTABLE."
    ],
    "hitLines": [
      "OW. LUCKY.",
      "RUDE."
    ],
    "fakeDeathLine1": "JUST KIDDING.",
    "fakeDeathLine2": "ANYWAY.",
    "mockLine": [
      "I LIVE.",
      "...NICE SHIRT."
    ],
    "retortLine": "IT WAS A GIFT.",
    "itemLabel": "THE COMEBACK!",
    "redemptionLine": "FINE. IT WAS GOOD."
  },
  "savior": {
    "itemName": "GIFT",
    "line1": "EXCUSE ME...",
    "line2": "I BROUGHT THE {ITEM}.",
    "sincereLine": "HEY {HOST}... YOU SAVED THE NIGHT."
  },
  "authority": {
    "entranceLine1": "A ONE-STAR REVIEW?!",
    "entranceLine2": "WHO DID THIS?",
    "turnGoodLine1": "FIVE STARS...",
    "turnGoodLine2": "LET'S DO THIS AGAIN SOMETIME.",
    "beggingLine": "PLEASE. FIVE STARS.",
    "failLine": "THE REVIEW STANDS.",
    "cardTitle": "THE BOSS HAS ARRIVED",
    "cardBody": [
      "{HOST}'S BOSS SAW A BAD REVIEW.",
      "CHASE THE GUESTS. BEG FOR FIVE STARS.",
      "DON'T GET CAUGHT."
    ]
  },
  "butterfingers": {
    "deleteAllLine": "DELETE ALL?",
    "deletedLine": "DELETED.",
    "allMyPhotosLine": "ALL MY PHOTOS."
  },
  "builder": {
    "epBCaption1": "THAT NIGHT, SOMEONE KEPT THINKING ABOUT IT.",
    "epBCaption2": "THEY WENT HOME.",
    "epBCaption3": "AND BUILT A GAME ABOUT THAT EXACT NIGHT.",
    "epBCaption4": "AND SHARED IT WITH EVERYONE.",
    "cardTitle": "TECH SUPPORT",
    "cardBody": [
      "SOMEONE CAN'T HEAR THE GAME.",
      "CHASE THEM DOWN.",
      "ASK IF THEY RESET IT."
    ],
    "cantHearLine": "I CAN'T HEAR THE MUSIC.",
    "resetQuestionLine": "DID YOU RESET IT?",
    "resetReplies": [
      "WHAT?",
      "IT'S JUST BEEPING.",
      "STILL NO SOUND."
    ],
    "resetFinalReply": "OH. IT WORKS NOW."
  },
  "introStory": {
    "scene1Lines": [
      "NOT LONG AGO,",
      "{HOST} HOSTED A NIGHT FOR SOME FRIENDS.",
      "THE STORIES THEY TOLD WERE VERY ORDINARY."
    ],
    "scene2Lines": [
      "THEY SAY {HOST} STILL WAITS BY THE DOOR...",
      "LISTENING."
    ],
    "scene4LinesWithSavior": [
      "YOU GOT THE {ITEM}!",
      "IT IS GREATLY APPRECIATED."
    ],
    "scene4LinesNoSavior": [
      "THE NIGHT WAS SAVED.",
      "EVERYONE HAD A GREAT TIME."
    ]
  },
  "rankNames": {
    "immaculate": "IMMACULATE",
    "comicTiming": "COMIC TIMING",
    "worst": "FRIEND WHO RUINS THE NIGHT"
  },
  "loseLine": "THE NIGHT IS RUINED.",
  "scene": "dinner"
};
