'use strict';
/* ======================================================================
   THE GAME NIGHT REGULARS -- generated by tools/generate.js from defense-sample-answers.json
   Do not hand-edit lightly -- re-running the generator will overwrite this
   file. See FULFILLMENT.md for the human-review steps this still needs
   before an order is actually delivered (content review is NOT automated).
   ====================================================================== */
const CONFIG = {
  "gameId": "defense-sample",
  "template": "defense",
  "title": {
    "lockupLines": [
      "THE GAME",
      "NIGHT REGULARS"
    ],
    "introPageTitle": "The Game Night Regulars",
    "gamePageTitle": "The Game Night Regulars -- Playable Demo"
  },
  "punchline": "THAT'S NOT HOW YOU PLAY THAT.",
  "host": {
    "name": "PRIYA",
    "sprite": "mohawk"
  },
  "music": {
    "customSongPath": null,
    "loops": {
      "dinner": "../../assets/audio/music/mission-plausible.ogg",
      "boss": "../../assets/audio/music/mischief-stroll.ogg",
      "chase": "../../assets/audio/music/drumming-sticks.ogg",
      "celebration": "../../assets/audio/music/space-cadet.ogg",
      "sad": "../../assets/audio/music/infinite-descent.ogg",
      "gameover": "../../assets/audio/music/game-over.ogg"
    },
    "introFallback": "../../assets/audio/music/night-at-the-beach.ogg"
  },
  "forbiddenWords": [],
  "defense": {
    "defending": "GAME NIGHT",
    "waves": [
      "PHONE NOTIFICATIONS",
      "THE RULES EXPLAINER",
      "THE UPSTAIRS NEIGHBORS",
      "THE RULES LAWYER",
      "A FLIPPED BOARD"
    ],
    "firstBossHeckle": "WRITE THAT DOWN, IT'S A PENALTY.",
    "finalBossQuirk": "STILL MAD ABOUT THE PARKING SPOT."
  },
  "cast": {
    "diner0": {
      "name": "THE FOURTH FRIEND",
      "spriteCol": 1,
      "spriteRow": 7,
      "anecdote": "Always up for anything."
    },
    "judge": {
      "name": "THE SCOREKEEPER",
      "anecdote": "Tracks points more carefully than the actual rulebook.",
      "spriteCol": 4,
      "spriteRow": 8,
      "sprite": "grandma"
    },
    "authority": {
      "name": "THE HOA PRESIDENT",
      "anecdote": "Has opinions about the driveway chalk.",
      "sprite": "beard"
    },
    "savior": {
      "name": "THE PEACEMAKER",
      "anecdote": "Steps in right before someone flips the table.",
      "sprite": "overalls"
    },
    "butterfingers": {
      "name": "THE ONE WHO KNOCKS THE BOARD",
      "anecdote": "Has ended three games with one elbow.",
      "spriteCol": 3,
      "spriteRow": 8,
      "sprite": "braid"
    },
    "builder": {
      "name": "THE GROUP'S SCORE APP",
      "anecdote": "Built this exact game during a rain delay.",
      "spriteCol": 2,
      "spriteRow": 8,
      "sprite": "vest"
    }
  },
  "rankNames": {
    "immaculate": "IMMACULATE",
    "comicTiming": "COMIC TIMING",
    "worst": "COULD USE MORE PRACTICE"
  }
};
