'use strict';
/* ======================================================================
   THE POWDER DAY CREW -- generated by tools/generate.js from flight-sample-answers.json
   Do not hand-edit lightly -- re-running the generator will overwrite this
   file. See FULFILLMENT.md for the human-review steps this still needs
   before an order is actually delivered (content review is NOT automated).
   ====================================================================== */
const CONFIG = {
  "gameId": "flight-sample",
  "template": "flight",
  "title": {
    "lockupLines": [
      "THE POWDER",
      "DAY CREW"
    ],
    "introPageTitle": "The Powder Day Crew",
    "gamePageTitle": "The Powder Day Crew -- Playable Demo"
  },
  "punchline": "SOMEHOW WE ALWAYS MAKE IT DOWN.",
  "host": {
    "name": "SAM",
    "sprite": "skigreen",
    "quotes": [
      "WE ALWAYS MAKE IT DOWN. EVENTUALLY.",
      "THIS IS FINE. THE SNOW IS FINE."
    ]
  },
  "music": {
    "customSongPath": null,
    "loops": {
      "dinner": "../../assets/audio/music/time-driving.ogg",
      "boss": "../../assets/audio/music/alpha-dance.ogg",
      "chase": "../../assets/audio/music/retro-beat.ogg",
      "celebration": "../../assets/audio/music/german-virtue.ogg",
      "sad": "../../assets/audio/music/sad-town.ogg",
      "gameover": "../../assets/audio/music/game-over.ogg"
    },
    "introFallback": "../../assets/audio/music/night-at-the-beach.ogg"
  },
  "forbiddenWords": [],
  "flight": {
    "beats": [
      "THE RENTAL SHOP LOST THE BOOT SIZES.",
      "SOMEONE PACKED SHORTS INSTEAD OF SNOW PANTS.",
      "THE CHAIRLIFT STOPPED FOR FORTY MINUTES.",
      "NOBODY COULD FIND THE CABIN IN THE DARK.",
      "THE HOT TUB WAS SOMEHOW STILL ICE COLD."
    ],
    "hazards": [
      "THE ICE PATCH",
      "THE WRONG TURN",
      "THE GONDOLA LINE",
      "THE VENDING MACHINE"
    ],
    "planeColor": "blue",
    "firstBossHeckle": "PIZZA, NOT FRENCH FRIES, ROOKIE.",
    "finalBossQuirk": "STILL MAD ABOUT THE WET BOOTS BY THE FIRE."
  },
  "cast": {
    "diner0": {
      "name": "THE FOURTH FRIEND",
      "spriteCol": 1,
      "spriteRow": 7,
      "anecdote": "Always up for anything.",
      "quotes": [
        "I'M ALWAYS UP FOR ANYTHING.",
        "SIGN ME UP FOR THE NEXT ROUND."
      ]
    },
    "judge": {
      "name": "THE SKI INSTRUCTOR",
      "anecdote": "Judges every turn from the lift line.",
      "spriteCol": 4,
      "spriteRow": 8,
      "sprite": "skipurple",
      "quotes": [
        "BEND YOUR KNEES. YOU NEVER BEND YOUR KNEES.",
        "I JUDGE EVERY TURN FROM THE LIFT LINE."
      ]
    },
    "authority": {
      "name": "THE LODGE MANAGER",
      "anecdote": "Remembers every pair of wet boots left by the fire.",
      "sprite": "grandma",
      "quotes": [
        "THE BOOTS WERE STILL WET BY THE FIRE.",
        "I REMEMBER EVERY PAIR OF WET BOOTS."
      ]
    },
    "savior": {
      "name": "THE ONE WITH SNACKS",
      "anecdote": "Always has one more granola bar than anyone asked for.",
      "sprite": "snowman",
      "quotes": [
        "I ALWAYS PACK ONE EXTRA GRANOLA BAR.",
        "SNACKS FIRST. QUESTIONS LATER."
      ]
    },
    "butterfingers": {
      "name": "THE ONE WHO DROPPED THE GOPRO",
      "anecdote": "Has lost count of how many lens caps are buried in the snow.",
      "spriteCol": 3,
      "spriteRow": 8,
      "sprite": "braid",
      "quotes": [
        "IT'S SOMEWHERE IN THE SNOW. PROBABLY.",
        "THE LENS CAP IS GONE FOREVER."
      ]
    },
    "builder": {
      "name": "THE GROUP'S MAP APP",
      "anecdote": "Built this exact game after the drive home.",
      "spriteCol": 2,
      "spriteRow": 8,
      "sprite": "bandana",
      "quotes": [
        "I BUILT THIS RIGHT AFTER THE DRIVE HOME.",
        "REROUTING. AGAIN."
      ]
    }
  },
  "rankNames": {
    "immaculate": "IMMACULATE",
    "comicTiming": "COMIC TIMING",
    "worst": "COULD USE MORE PRACTICE"
  },
  "extras": [
    {
      "name": "THE FRIEND WHO STAYED IN THE LODGE",
      "sprite": "strawhat",
      "quotes": [
        "I WATCHED FROM THE WINDOW. IT LOOKED COLD.",
        "SOMEONE HAD TO GUARD THE HOT COCOA."
      ]
    }
  ]
};
