'use strict';
/* ======================================================================
   THE WEEKEND LEAGUE -- generated by tools/generate.js from gallery-sample-answers.json
   Do not hand-edit lightly -- re-running the generator will overwrite this
   file. See FULFILLMENT.md for the human-review steps this still needs
   before an order is actually delivered (content review is NOT automated).
   ====================================================================== */
const CONFIG = {
  "gameId": "gallery-sample",
  "template": "gallery",
  "title": {
    "lockupLines": [
      "THE WEEKEND",
      "LEAGUE"
    ],
    "introPageTitle": "The Weekend League",
    "gamePageTitle": "The Weekend League -- Playable Demo"
  },
  "punchline": "THAT'S SO ON BRAND.",
  "host": {
    "name": "JORDAN"
  },
  "music": {
    "customSongPath": null,
    "loops": {
      "dinner": "../../assets/audio/music/wacky-waiting.ogg",
      "boss": "../../assets/audio/music/cheerful-annoyance.ogg",
      "chase": "../../assets/audio/music/polka-train.ogg",
      "celebration": "../../assets/audio/music/swinging-pants.ogg",
      "sad": "../../assets/audio/music/sad-descent.ogg",
      "gameover": "../../assets/audio/music/game-over.ogg"
    },
    "introFallback": "../../assets/audio/music/night-at-the-beach.ogg"
  },
  "forbiddenWords": [],
  "gallery": {
    "targets": [
      "FANTASY DRAFT SPEECHES",
      "SPREADSHEET AT BRUNCH",
      "THE PARKING INCIDENT",
      "SOCKS WITH SANDALS",
      "ARTISANAL MAC N CHEESE",
      "NARRATES OWN COOKING"
    ],
    "firstBossHeckle": "YOUR AIM IS AS BAD AS YOUR TAKES.",
    "finalBossQuirk": "ALWAYS ADJUSTS THEIR GLASSES BEFORE LYING."
  },
  "cast": {
    "diner0": {
      "name": "THE FOURTH FRIEND",
      "spriteCol": 1,
      "spriteRow": 7,
      "anecdote": "Always up for anything."
    },
    "judge": {
      "name": "THE COMMISSIONER",
      "anecdote": "Runs the fantasy league like it is federal law.",
      "spriteCol": 4,
      "spriteRow": 8,
      "sprite": "grandma"
    },
    "authority": {
      "name": "THE LANDLORD",
      "anecdote": "Shows up personally over a noise complaint.",
      "sprite": "bandana"
    },
    "savior": {
      "name": "THE DESIGNATED DRIVER",
      "anecdote": "Always sober, always has snacks in the car.",
      "sprite": "vest"
    },
    "butterfingers": {
      "name": "THE ONE WHO DROPS EVERYTHING",
      "anecdote": "Has broken three different house rules, literally.",
      "spriteCol": 3,
      "spriteRow": 8,
      "sprite": "braid"
    },
    "builder": {
      "name": "THE GROUP'S TECH GUY",
      "anecdote": "Built this exact game on a Tuesday night.",
      "spriteCol": 2,
      "spriteRow": 8,
      "sprite": "mohawk"
    }
  },
  "rankNames": {
    "immaculate": "IMMACULATE",
    "comicTiming": "COMIC TIMING",
    "worst": "COULD USE MORE PRACTICE"
  }
};
