'use strict';
/* ======================================================================
   THE APARTMENT HUNTERS -- generated by tools/generate.js from mission-sample-answers.json
   Do not hand-edit lightly -- re-running the generator will overwrite this
   file. See FULFILLMENT.md for the human-review steps this still needs
   before an order is actually delivered (content review is NOT automated).
   ====================================================================== */
const CONFIG = {
  "gameId": "mission-sample",
  "template": "mission",
  "title": {
    "lockupLines": [
      "THE APARTMENT",
      "HUNTERS"
    ],
    "introPageTitle": "The Apartment Hunters",
    "gamePageTitle": "The Apartment Hunters -- Playable Demo"
  },
  "punchline": "WE FOUND IT. IT HAS LAUNDRY.",
  "host": {
    "name": "DESHAWN",
    "sprite": "overalls",
    "quotes": [
      "WE FOUND IT. IT HAS LAUNDRY.",
      "IN-UNIT LAUNDRY IS NON-NEGOTIABLE."
    ]
  },
  "music": {
    "customSongPath": null,
    "loops": {
      "dinner": "../../assets/audio/music/time-driving.ogg",
      "boss": "../../assets/audio/music/alpha-dance.ogg",
      "chase": "../../assets/audio/music/retro-beat.ogg",
      "celebration": "../../assets/audio/music/german-virtue.ogg",
      "sad": "../../assets/audio/music/sad-town.ogg",
      "gameover": "../../assets/audio/music/game-over.ogg"
    },
    "introFallback": "../../assets/audio/music/night-at-the-beach.ogg"
  },
  "forbiddenWords": [],
  "mission": {
    "mission": "FIND A PLACE WITH IN-UNIT LAUNDRY",
    "swarms": [
      "THE BAD LISTINGS",
      "GHOSTING LANDLORDS",
      "SURPRISE FEES",
      "THE BRUTAL COMMUTE",
      "ROOMMATE RED FLAGS"
    ],
    "shipColor": "orange",
    "firstBossHeckle": "IT WON'T LAST AT THIS PRICE.",
    "finalBossQuirk": "STILL MAD ABOUT THAT ONE EMAIL."
  },
  "cast": {
    "diner0": {
      "name": "THE FOURTH FRIEND",
      "spriteCol": 1,
      "spriteRow": 7,
      "anecdote": "Always up for anything.",
      "quotes": [
        "I BROUGHT SNACKS TO EVERY VIEWING.",
        "I'M HERE FOR MORAL SUPPORT AND SNACKS."
      ]
    },
    "judge": {
      "name": "THE BROKER",
      "anecdote": "Charges a fee for texting back.",
      "spriteCol": 4,
      "spriteRow": 8,
      "sprite": "grandma",
      "quotes": [
        "THAT'S A PROCESSING FEE FOR TEXTING BACK.",
        "THE LISTING PHOTOS WERE... GENEROUS."
      ]
    },
    "authority": {
      "name": "THE LANDLORD",
      "anecdote": "Has never once fixed the radiator.",
      "sprite": "beard",
      "quotes": [
        "THE RADIATOR IS FINE. IT'S CHARACTER.",
        "I'LL LOOK INTO IT. EVENTUALLY."
      ]
    },
    "savior": {
      "name": "THE CO-SIGNER",
      "anecdote": "Always has a backup plan and a spare key.",
      "sprite": "vest",
      "quotes": [
        "I ALWAYS HAVE A BACKUP PLAN.",
        "HERE'S THE SPARE KEY, JUST IN CASE."
      ]
    },
    "butterfingers": {
      "name": "THE ONE WHO DROPS THE KEYS",
      "anecdote": "Has been locked out three times this month.",
      "spriteCol": 3,
      "spriteRow": 8,
      "sprite": "braid",
      "quotes": [
        "LOCKED OUT AGAIN. THIRD TIME THIS MONTH.",
        "THE KEYS ARE SOMEWHERE. PROBABLY."
      ]
    },
    "builder": {
      "name": "THE SPREADSHEET",
      "anecdote": "Built a spreadsheet ranking every listing by laundry access.",
      "spriteCol": 2,
      "spriteRow": 8,
      "sprite": "squire",
      "quotes": [
        "I RANKED EVERY LISTING BY LAUNDRY ACCESS.",
        "THE SPREADSHEET HAS COLOR CODING."
      ]
    }
  },
  "rankNames": {
    "immaculate": "IMMACULATE",
    "comicTiming": "COMIC TIMING",
    "worst": "COULD USE MORE PRACTICE"
  },
  "extras": [
    {
      "name": "THE FRIEND WHO ALREADY HAS A PLACE",
      "sprite": "villager",
      "quotes": [
        "I FOUND MINE IN ONE WEEKEND. SORRY.",
        "GOOD LUCK OUT THERE."
      ]
    }
  ]
};
